### Open the CO2 notebook we have worked on 

#### The goal is to use the month and year attributes/features as a categorical variable to use in multiple regression
- Do you understand why it's problematic to leave it as an integer type? 

#### 1. Load the co2 data

In [1]:
from natee_mindy_cliff_CodeWarmup_06_07_19 import df  # import co2 from friday's warmup py file

   Year  Month  Interpolated Average
0  1958      3                315.71
1  1958      4                317.45
2  1958      5                317.50
3  1958      6                317.10
4  1958      7                315.86
Index(['Year', 'Month', 'CO2', 'Interpolated Average', 'Season Trend', 'Date'], dtype='object')

/Users/mindy/Documents/flatiron_school/code_sample/dc_ds_06_03_19/module_1/morning_warm_up/week_2/natee_mindy_cliff_CodeWarmup_06_07_19.py:100: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  npdata=df.iloc[:,[2,6]].as_matrix() #converting to numpy array

In [ ]:
df.head()

#### 2. Follow all steps from previous notebook to get it to the state where we have 4 columns (year, month, day, CO2)

In [2]:
df_analysis = df[['Year','Month','CO2']]  # select the 3 columns

In [3]:
df_analysis['Day'] = 15  # add day column

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_analysis.info()

In [4]:
import pandas as pd
import numpy as np

#### 3. Transform month and year to categorical variables 

`Use pd.dummy`

In [5]:
df_analysis = pd.get_dummies(df_analysis, columns=['Year', 'Month'])

In [ ]:
df_analysis.head()

#### 4. For practice purposes only let's create a function that gets a df and a column name and outputs a normalized column
 - a column of our choice --> here we'll test the CO2 column 
`use the np.mean function and np.std `

In [6]:
def normed_columns(DF, colname):
    average = np.mean(DF[colname])
    se = np.std(DF[colname])
    return (DF[colname]-average)/se

In [7]:
normed_columns(df_analysis, 'CO2').iloc[-1]  # last value of normalized z data for CO2

1.235946247903001

Push all your changes to github

6. Open the suicide_rates file and notebook
7. Apply normalization and dummies wherever seems appropriate to you to prepare the data for some analysis - this is a discussion to be done in pairs or triplets.
8. Push any changes to github
9. Send your Coach the last value of normalized C02 you have recieved

In [8]:
suicide_df = pd.read_csv('suicides.csv')

In [9]:
suicide_df.tail()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [10]:
suicide_df.columns

Index(['country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation'],
      dtype='object')

In [11]:
# normalization (zscale for suicides/100k pop, gdp_per_capita)
# suicides/100k accounts for no. of suicdies and population columns, gdp_per_capita is better than per year 
for col in ['suicides/100k pop','gdp_per_capita ($)']:
    suicide_df[col] = normed_columns(suicide_df, col)

In [12]:
suicide_df.describe()

,year,suicides_no,population,suicides/100k pop,HDI for year,gdp_per_capita ($)
count,27820.000000,27820.000000,2.782000e+04,2.782000e+04,8364.000000,2.782000e+04
mean,2001.258375,242.574407,1.844794e+06,-4.203766e-15,0.776601,-8.307358e-16
std,8.469055,902.047917,3.911779e+06,1.000018e+00,0.093367,1.000018e+00
min,1985.000000,0.000000,2.780000e+02,-6.759128e-01,0.483000,-8.797192e-01
25%,1995.000000,3.000000,9.749850e+04,-6.273926e-01,0.713000,-7.105044e-01
50%,2002.000000,25.000000,4.301500e+05,-3.600040e-01,0.779000,-3.968005e-01
75%,2008.000000,131.000000,1.486143e+06,2.006154e-01,0.855000,4.239654e-01
max,2016.000000,22338.000000,4.380521e+07,1.118886e+01,0.944000,5.796800e+00

In [13]:
suicide_df.groupby('generation').age.value_counts()

generation       age
Boomers          35-54 years    3030
                 25-34 years    1154
                 55-74 years     806
G.I. Generation  75+ years      2114
                 55-74 years     630
Generation X     25-34 years    2682
                 15-24 years    2114
                 35-54 years     982
                 5-14 years      630
Generation Z     5-14 years     1470
Millenials       15-24 years    2528
                 5-14 years     2510
                 25-34 years     806
Silent           55-74 years    3206
                 75+ years      2528
                 35-54 years     630
Name: age, dtype: int64

In [14]:
# set country, generation to dummy variables age, as each generation includes multiple age groups 

suicide_df = pd.get_dummies(suicide_df, columns=['age'])  # age incldues more info than generation

In [15]:
suicide_df

,country,year,sex,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,age_15-24 years,age_25-34 years,age_35-54 years,age_5-14 years,age_55-74 years,age_75+ years
0,Albania,1987,male,21,312900,-0.322032,Albania1987,NaN,"2,156,624,900",-0.850864,Generation X,1,0,0,0,0,0
1,Albania,1987,male,16,308000,-0.402196,Albania1987,NaN,"2,156,624,900",-0.850864,Silent,0,0,1,0,0,0
2,Albania,1987,female,14,289700,-0.421182,Albania1987,NaN,"2,156,624,900",-0.850864,Generation X,1,0,0,0,0,0
3,Albania,1987,male,1,21800,-0.433839,Albania1987,NaN,"2,156,624,900",-0.850864,G.I. Generation,0,0,0,0,0,1
4,Albania,1987,male,9,274300,-0.502928,Albania1987,NaN,"2,156,624,900",-0.850864,Boomers,0,1,0,0,0,0
5,Albania,1987,female,1,35600,-0.527715,Albania1987,NaN,"2,156,624,900",-0.850864,G.I. Generation,0,0,0,0,0,1
6,Albania,1987,female,6,278800,-0.562523,Albania1987,NaN,"2,156,624,900",-0.850864,Silent,0,0,1,0,0,0
7,Albania,1987,female,4,257200,-0.593639,Albania1987,NaN,"2,156,624,900",-0.850864,Boomers,0,1,0,0,0,0
8,Albania,1987,male,1,137500,-0.637413,Albania1987,NaN,"2,156,624,900",-0.850864,G.I. Generation,0,0,0,0,1,0
9,Albania,1987,female,0,311000,-0.675913,Albania1987,NaN,"2,156,624,900",-0.850864,Generation X,0,0,0,1,0,0
10,Albania,1987,female,0,144600,-0.675913,Albania1987,NaN,"2,156,624,900",-0.850864,G.I. Generation,0,0,0,0,1,0
11,Albania,1987,male,0,338200,-0.675913,Albania1987,NaN,"2,156,624,900",-0.850864,Generation X,0,0,0,1,0,0
12,Albania,1988,female,2,36400,-0.386374,Albania1988,NaN,"2,126,000,000",-0.852293,G.I. Generation,0,0,0,0,0,1
13,Albania,1988,male,17,319200,-0.394812,Albania1988,NaN,"2,126,000,000",-0.852293,Generation X,1,0,0,0,0,0
14,Albania,1988,male,1,22300,-0.439640,Albania1988,NaN,"2,126,000,000",-0.852293,G.I. Generation,0,0,0,0,0,1
15,Albania,1988,male,14,314100,-0.440695,Albania1988,NaN,"2,126,000,000",-0.852293,Silent,0,0,1,0,0,0
16,Albania,1988,male,4,140200,-0.525606,Albania1988,NaN,"2,126,000,000",-0.852293,G.I. Generation,0,0,0,0,1,0
17,Albania,1988,female,8,295600,-0.532989,Albania1988,NaN,"2,126,000,000",-0.852293,Generation X,1,0,0,0,0,0
18,Albania,1988,female,3,147500,-0.568852,Albania1988,NaN,"2,126,000,000",-0.852293,G.I. Generation,0,0,0,0,1,0
19,Albania,1988,female,5,262400,-0.575181,Albania1988,NaN,"2,126,000,000",-0.852293,Boomers,0,1,0,0,0,0
20,Albania,1988,male,5,279900,-0.581509,Albania1988,NaN,"2,126,000,000",-0.852293,Boomers,0,1,0,0,0,0
21,Albania,1988,female,4,284500,-0.601550,Albania1988,NaN,"2,126,000,000",-0.852293,Silent,0,0,1,0,0,0
22,Albania,1988,female,0,317200,-0.675913,Albania1988,NaN,"2,126,000,000",-0.852293,Generation X,0,0,0,1,0,0
23,Albania,1988,male,0,345000,-0.675913,Albania1988,NaN,"2,126,000,000",-0.852293,Generation X,0,0,0,1,0,0
24,Albania,1989,male,2,22500,-0.207060,Albania1989,NaN,"2,335,124,988",-0.848905,G.I. Generation,0,0,0,0,0,1
25,Albania,1989,male,18,283600,-0.341018,Albania1989,NaN,"2,335,124,988",-0.848905,Boomers,0,1,0,0,0,0
26,Albania,1989,male,15,318400,-0.427510,Albania1989,NaN,"2,335,124,988",-0.848905,Silent,0,0,1,0,0,0
27,Albania,1989,male,6,142100,-0.453353,Albania1989,NaN,"2,335,124,988",-0.848905,G.I. Generation,0,0,0,0,1,0
28,Albania,1989,male,12,323500,-0.480250,Albania1989,NaN,"2,335,124,988",-0.848905,Generation X,1,0,0,0,0,0
29,Albania,1989,female,7,288600,-0.547756,Albania1989,NaN,"2,335,124,988",-0.848905,Silent,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27790,Uzbekistan,2012,female,148,2556673,-0.370552,Uzbekistan2012,0.668,"51,821,573,338",-0.789023,Millenials,0,1,0,0,0,0
27791,Uzbekistan,2012,female,89,3474788,-0.540900,Uzbekistan2012,0.668,"51,821,573,338",-0.789023,Generation X,0,0,1,0,0,0
27792,Uzbekistan,2012,male,67,2701361,-0.545119,Uzbekistan2012,0.668,"51,821,573,338",-0.789023,Generation Z,0,0,0,1,0,0
27793,Uzbekistan,2012,female,25,1283060,-0.573071,Uzbekistan2012,0.668,"51,821,573,338",-0.789023,Boomers,0,0,0,0,1,0
27794,Uzbekistan,2012,female,4,338557,-0.613680,Uzbekistan2012,0.668,"51,821,573,338",-0.789023,Silent,0,0,0,0,0,1
27795,Uzbekistan,2012,female,16,2578408,-0.643214,Uzbekistan2012,0.668,"51,821,573,338",-0.789023,Generation Z,0,0,0,1,0,0
27796,Uzbekistan,2013,male,481,3346411,0.081952,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Generation X,0,0,1,0,0,0
27797,Uzbekistan,2013,male,328,2644648,-0.021945,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Millenials,0,1,0,0,0,0
27798,Uzbekistan,2013,female,323,3039740,-0.115293,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Millenials,1,0,0,0,0,0
27799,Uzbekistan,2013,male,320,3171202,-0.143773,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Millenials,1,0,0,0,0,0
27800,Uzbekistan,2013,male,119,1202790,-0.154321,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Boomers,0,0,0,0,1,0
27801,Uzbekistan,2013,male,13,221002,-0.365805,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Silent,0,0,0,0,0,1
27802,Uzbekistan,2013,female,146,2647820,-0.385319,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Millenials,0,1,0,0,0,0
27803,Uzbekistan,2013,female,99,3547895,-0.528770,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Generation X,0,0,1,0,0,0
27804,Uzbekistan,2013,female,8,345180,-0.553557,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Silent,0,0,0,0,0,1
27805,Uzbekistan,2013,male,61,2720938,-0.557777,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Generation Z,0,0,0,1,0,0
27806,Uzbekistan,2013,female,21,1356298,-0.594167,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Boomers,0,0,0,0,1,0
27807,Uzbekistan,2013,female,31,2595000,-0.613153,Uzbekistan2013,0.672,"57,690,453,461",-0.779175,Generation Z,0,0,0,1,0,0
27808,Uzbekistan,2014,male,519,3421300,0.124143,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Generation X,0,0,1,0,0,0
27809,Uzbekistan,2014,male,318,2739150,-0.063609,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Millenials,0,1,0,0,0,0
27810,Uzbekistan,2014,female,347,2992817,-0.064664,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Millenials,1,0,0,0,0,0
27811,Uzbekistan,2014,male,144,1271111,-0.078376,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Boomers,0,0,0,0,1,0
27812,Uzbekistan,2014,male,347,3126905,-0.090506,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Millenials,1,0,0,0,0,0
27813,Uzbekistan,2014,male,17,224995,-0.277203,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Silent,0,0,0,0,0,1
27814,Uzbekistan,2014,female,162,2735238,-0.363696,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Millenials,0,1,0,0,0,0
27815,Uzbekistan,2014,female,107,3620833,-0.519804,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Generation X,0,0,1,0,0,0
27816,Uzbekistan,2014,female,9,348465,-0.539845,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Silent,0,0,0,0,0,1
27817,Uzbekistan,2014,male,60,2762158,-0.561468,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Generation Z,0,0,0,1,0,0
27818,Uzbekistan,2014,female,44,2631600,-0.587838,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Generation Z,0,0,0,1,0,0
27819,Uzbekistan,2014,female,21,1438935,-0.598913,Uzbekistan2014,0.675,"63,067,077,179",-0.770757,Boomers,0,0,0,0,1,0